### ISSUE TITLE
Crate ownership on crates.io

### ISSUE THREAD

**Issue by pulsastrix** [TotalKrill/libcoap-sys#1]
Hi,

As part of the masters computer science project [NAMIB](https://namib.me/en) at the University of Bremen we have written our own wrapper around libcoap, which can be found [here](https://github.com/namib-project/libcoap-rs).

Because this repository has been inactive for quite some time now, we wanted to kindly ask if you would be fine with transferring the crate names on crates.io (https://crates.io/crates/libcoap-rs and https://crates.io/crates/libcoap-sys) over to me so that we can publish our crates under this name.

**Comment by TotalKrill** [comment]
sorry, missed this on my inbox. Ofcourse I can

**Comment by pulsastrix** [comment]
Thank you very much!
